// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swxpidinkniuvtusjtrh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3eHBpZGlua25pdXZ0dXNqdHJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNTczNjIsImV4cCI6MjA2MzgzMzM2Mn0.lEupgCGz7pcmfGBSThGlBF9dXo2iqd6RyxiG0_EvbvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);